name: cf-dmol
description: CF dmol wrapper
author: ' '
inputs:
  operationId:
    description: ' '
  mtaId:
    description: ' '
  last:
    description: ' '
  directory:
    description: ' '
  deoployServiceUrl:
    description: ' '
  saveDMOLToArtifactory:
    description: ' '
  dmolArtifactName:
    description: ' '
  flags:
    description: CF command flags text
    required: false
  manualLogin:
    description: ' '
    required: false
  apiUrl:
    description: ' '
    required: false
  organization:
    description: ' '
    required: false
  space:
    description: ' '
    required: false
  user:
    description: ' '
    required: false
  password:
    description: ' '
    required: false
  skipSSLValidation:
    description: ' '
    required: false
  origin:
    description: ' '
    required: false
  credentials:
    description: ' '
    required: false
runs:
  using: node16
  main: index.js
  pre: ../login/index.js
  post: ../logout/index.js
